type: object
title: addProductDescription
description: Schema for a product description.
properties:
  description:
    type: string
    description: The description of a product.
  is_init:
    type: boolean
    description: Check init this description