type: object
title: ProductImage
description: Schema for a product image.
properties:
  path:
    type: string
    description: The path of a image in server.
  is_primary:
    type: boolean
    description: Check image is primary.