type: object
title: ProductDescription
description: Schema for a product description.
properties:
  description:
    type: string
    description: The description of a product.
  upload_date:
    type: string
    format: date-time
    description: The date upload this description.