type: object
title: Product
description: Schema for a product request.
properties:
  category_id:
    type: string
    description: The password of a category.
  name:
    type: string
    description: The name of a product.
  end_at:
    type: string
    format: date-time
    description: The timestamp end bidding product.