openapi: 3.0.3
info:
  title: Blog API
  description: The API specification for Blog API
  version: 0.0.1
servers:
  - url: "{scheme}://{address}:{port}/{basePath}"
    description: A custom API server
    variables:
      scheme:
        default: http
      address:
        default: localhost
      port:
        enum:
          - "3000"
        default: "3000"
      basePath:
        default: v0
components:
  schemas:
    $ref: "./schemas/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
paths:
  /auths/login:
    $ref: "./resources/auths/login.yaml"
  /auths/refreshToken:
    $ref: "./resources/auths/refreshToken.yaml"
  /users:
    $ref: "./resources/users/_index.yaml"
  /users/{Id}:
    $ref: "./resources/users/userId/_index.yaml"
  /users/{Id}/resetPass:
    $ref: "./resources/users/userId/resetPass.yaml"
  /users/{Id}/forgotPass:
    $ref: "./resources/users/userId/forgotPass.yaml"
