openapi: 3.0.3
info:
  title: Blog API
  description: The API specification for Blog API
  version: 0.0.1
servers:
  - url: "{scheme}://{address}:{port}/{basePath}"
    description: A custom API server
    variables:
      scheme:
        default: http
      address:
        default: localhost
      port:
        enum:
          - "3000"
        default: "3000"
      basePath:
        default: api
components:
  securitySchemes:
    accessAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    refreshAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT   
    tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT   
  schemas:
    $ref: "./schemas/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
security:
  - accessAuth: []
  - refreshAuth: []   
paths:
  /auth/:
    $ref: "./resources/auth/_index.yaml"
  /auth/register:
    $ref: "./resources/auth/register.yaml"
  /auth/reset:
    $ref: "./resources/auth/reset.yaml"
  /auth/verify:
    $ref: "./resources/auth/verify.yaml"
  /auth/logout:
    $ref: "./resources/auth/logout.yaml"
  /auth/refresh:
    $ref: "./resources/auth/refresh.yaml"

  # /users:
  #   $ref: "./resources/users/_index.yaml"
  # /users/{Id}:
  #   $ref: "./resources/users/userId/_index.yaml"

  /products:
    $ref: "./resources/products/_index.yaml"
  /products/{Id}:
    $ref: "./resources/products/productId/_index.yaml"
  /products/{Id}/image:
    $ref: "./resources/products/productId/image.yaml"
  /products/{Id}/description:
    $ref: "./resources/products/productId/description.yaml"
  
  # /images:
  #   $ref: "./resources/images/_index.yaml"
