openapi: 3.0.3
info:
  title: Blog API
  description: The API specification for Blog API
  version: 0.0.1
servers:
  - url: "{scheme}://{address}:{port}/{basePath}"
    description: A custom API server
    variables:
      scheme:
        default: http
      address:
        default: localhost
      port:
        enum:
          - "3000"
        default: "3000"
      basePath:
        default: api
components:
  securitySchemes:
    accessAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    refreshAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT   
    tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT   
  schemas:
    $ref: "./schemas/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
security:
  - accessAuth: []
  - refreshAuth: []   
paths:
  /auth/:
    $ref: "./resources/auth/_index.yaml"
  /auth/register:
    $ref: "./resources/auth/register.yaml"
  /auth/reset:
    $ref: "./resources/auth/reset.yaml"
  /auth/verify:
    $ref: "./resources/auth/verify.yaml"
  /auth/logout:
    $ref: "./resources/auth/logout.yaml"
  /auth/refresh:
    $ref: "./resources/auth/refresh.yaml"

  /categorys:
    $ref: "./resources/category/_index.yaml"
  /categorys/{id}/childcategory:
    $ref: "./resources/category/categoryId/childcategory.yaml"
  /categorys/{id}:
    $ref: "./resources/category/categoryId/_index.yaml"

  /biddings:
    $ref: "./resources/bidding/_index.yaml"
  /biddings/buyProduct:
    $ref: "./resources/bidding/buyProduct.yaml"
  /biddings/autoBidding:
    $ref: "./resources/bidding/autoBidding.yaml"
  /biddings/autoBidding/{Id}:
    $ref: "./resources/bidding/autoBidding/_index.yaml"
  /biddings/rejectBidding/{Id}:
    $ref: "./resources/bidding/rejectBidding/_index.yaml"
  /biddings/biddingPermission:
    $ref: "./resources/biddingPermission/_index.yaml"
  /biddings/biddingRequest:
    $ref: "./resources/biddingRequest/_index.yaml"
  /users/point:
    $ref: "./resources/users/userId/point.yaml"
  /users/bidding:
    $ref: "./resources/users/bidding.yaml"
  /users:
    $ref: "./resources/users/_index.yaml"
  /users/Email:
    $ref: "./resources/users/email.yaml"
    
  /users/all:
    $ref: "./resources/users/all.yaml"
  /users/role:
    $ref: "./resources/users/role.yaml"
  /users/requestSeller:
    $ref: "./resources/users/requestSeller.yaml"
  /users/rate:
    $ref: "./resources/users/rate.yaml"
  /users/productCanRate:
    $ref: "./resources/users/productsCanRate.yaml"
  /users/watchlist:
    $ref: "./resources/users/watchlist.yaml"

  /products:
    $ref: "./resources/products/_index.yaml"
  /products/seller:
    $ref: "./resources/products/seller.yaml"
  /products/{Id}:
    $ref: "./resources/products/productId/_index.yaml"
  /products/{Id}/image:
    $ref: "./resources/products/productId/image.yaml"
  /products/{Id}/image/{imageId}:
    $ref: "./resources/products/productId/imageId/_index.yaml"
  /products/{Id}/description:
    $ref: "./resources/products/productId/description.yaml"
  /products/{Id}/bidding:
    $ref: "./resources/products/productId/bidding.yaml"
  /products/won:
    $ref: "./resources/products/won.yaml"
  /products/bidding:
    $ref: "./resources/products/bidding.yaml"
  /products/active:
    $ref: "./resources/products/active.yaml"
  /products/inactive:
    $ref: "./resources/products/inactive.yaml"