get:
  operationId: getProductsNoRate
  summary: Get all product user can rate but no rate.
  responses:
    "200":
      description: An array products.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../../schemas/Product.yaml"
    "401":
      $ref: "../../../responses/Error.yaml"
    "404":
      $ref: "../../../responses/Error.yaml"
    "500":
      $ref: "../../../responses/Error.yaml"
    default:
      $ref: "../../../responses/Error.yaml"
  tags:
    - users